# Generated by Django 2.2 on 2021-03-20 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=300, verbose_name='Nome Completo')),
                ('sexo', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], verbose_name='Gênero')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('ddd', models.CharField(max_length=4, verbose_name='DDD')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('ddd2', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD')),
                ('telefone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone Fixo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações sobre o visitante')),
                ('user_add', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='portaria_visitante_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='portaria_visitante_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
