# Generated by Django 2.2 on 2021-04-14 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVisitante',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_add', models.DateTimeField(blank=True, editable=False)),
                ('date_upd', models.DateTimeField(blank=True, editable=False)),
                ('nome', models.CharField(max_length=300, verbose_name='Nome Completo')),
                ('sexo', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], verbose_name='Gênero')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('ddd', models.CharField(max_length=4, verbose_name='DDD')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('ddd2', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD')),
                ('telefone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone Fixo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações sobre o visitante')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_add', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical visitante',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
